import express from 'express'
import crypto from 'node:crypto'
import path from 'node:path'
import { config, root, assertProductionReady } from '../config.js'
import { mail } from '../mail.js'
import { encryptSensitive, decryptSensitive, matchTotpStep } from '../security.js'
import { getPool, sql, one, many, tx, migrate, closePool, id, now, sha256, hashPassword, verifyPassword, publicUser, pagination } from './pool.js'
import { Users, Sessions, Professionals, Notifications, Bookings, Analytics, Admin, audit } from './repositories.js'
import Stripe from 'stripe'
import { canViewBooking, canEditBooking, canReviewBooking } from './authorization.js'
import { redisRateLimit, redisGetJson, redisSetJson, redisPing, closeRedis } from '../redis.js'
import { log, requestId } from '../logger.js'
import { observeRequest, metricsText } from '../metrics.js'
import { queueStats } from '../jobs.js'
import { verificationObjectKey, putVerificationObject, getVerificationObject, deleteVerificationObject, storageReady, createTemporaryDocumentSignature, verifyTemporaryDocumentSignature } from '../object-storage.js'
import { APP_VERSION, RELEASE_CHANNEL } from '../version.js'

assertProductionReady()
await migrate()

const app=express(); if(config.trustProxy)app.set('trust proxy',1); app.disable('x-powered-by')
app.use((req,res,next)=>{const rid=requestId(req.headers['x-request-id']);req.requestId=rid;res.setHeader('X-Request-ID',rid);const t=process.hrtime.bigint();res.on('finish',()=>{const ms=Number(process.hrtime.bigint()-t)/1e6;observeRequest(req.method,res.statusCode,ms);const meta={requestId:rid,method:req.method,path:req.path,status:res.statusCode,durationMs:Number(ms.toFixed(2))};if(res.statusCode>=500)log.error('http.request',meta);else if(ms>=config.observability.slowRequestMs)log.warn('http.slow_request',meta)});next()})
const SESSION_COOKIE='meleo_session'; const SESSION_TTL_MS=30*86400000; const ADMIN_SESSION_TTL_MS=config.admin.sessionTtlHours*3600000
const PASSWORD_MIN=8
const str=(v,max=500)=>String(v??'').trim().slice(0,max)
const isEmail=v=>/^[^\s@]+@[^\s@]+\.[a-z]{2,}$/i.test(String(v||''))
const isDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))&&!Number.isNaN(Date.parse(v))
const isTime=v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(v||''))
const cookieNamed=(req,name)=>{const raw=String(req.headers.cookie||'');const safe=String(name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const m=raw.match(new RegExp('(?:^|;\\s*)'+safe+'=([^;]+)'));return m?decodeURIComponent(m[1]):''}
const setSessionCookie=(res,t,maxAge=SESSION_TTL_MS)=>res.cookie(SESSION_COOKIE,t,{httpOnly:true,secure:config.isHosted,sameSite:'lax',maxAge,path:'/'})
const clearSessionCookie=res=>res.clearCookie(SESSION_COOKIE,{httpOnly:true,secure:config.isHosted,sameSite:'lax',path:'/'})
const newToken=()=>crypto.randomBytes(32).toString('hex')
const fingerprint=(...parts)=>sha256(parts.join('|'))
function fileKey(){return crypto.createHash('sha256').update(config.security.sensitiveDataKey||'dev-only-insecure-key').digest()}
function encryptFileBuffer(buffer){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',fileKey(),iv),body=Buffer.concat([cipher.update(buffer),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body])}
function decryptFileBuffer(buffer){const iv=buffer.subarray(0,12),tag=buffer.subarray(12,28),body=buffer.subarray(28),dec=crypto.createDecipheriv('aes-256-gcm',fileKey(),iv);dec.setAuthTag(tag);return Buffer.concat([dec.update(body),dec.final()])}

const PLANS={
 basic:{id:'basic',name:'BASIC',price:9.99,currency:'EUR',interval:'month',recommended:false,features:['Δημόσιο επαγγελματικό προφίλ','Αιτήματα και διαχείριση κρατήσεων','Περιοχή & ακτίνα εξυπηρέτησης','Βασικά στατιστικά']},
 premium:{id:'premium',name:'PREMIUM',price:14.99,currency:'EUR',interval:'month',recommended:true,features:['Όλα τα BASIC','Σήμανση «Προτεινόμενος»','Προτεραιότητα στην κατάταξη αποτελεσμάτων','Advanced profile analytics']}
}
const isPlan=p=>p==='basic'||p==='premium'
let stripe=null; const getStripe=()=>config.stripeEnabled?(stripe||(stripe=new Stripe(config.stripe.secretKey,{apiVersion:'2025-06-30.basil',maxNetworkRetries:2,timeout:20000}))):null
const priceIdFor=plan=>plan==='premium'?config.stripe.pricePremium:config.stripe.priceBasic
const lineItemFor=plan=>priceIdFor(plan)?{price:priceIdFor(plan),quantity:1}:{quantity:1,price_data:{currency:'eur',unit_amount:Math.round(PLANS[plan].price*100),recurring:{interval:'month'},product_data:{name:`MELEO Professional ${PLANS[plan].name}`,metadata:{plan}}}}
const mapStripeStatus=s=>['active','trialing'].includes(s)?'active':s==='past_due'?'past_due':['canceled','unpaid','incomplete_expired','paused'].includes(s)?'cancelled':'pending'
const allowsVisibility=p=>p?.subscriptionStatus==='active'||(p?.subscriptionStatus==='past_due'&&p?.pastDueSince&&(Date.now()-new Date(p.pastDueSince).getTime())<=config.security.subscriptionGraceDays*86400000)

app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), payment=(self), geolocation=(self)');res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Content-Security-Policy',["default-src 'self'","script-src 'self'","style-src 'self' 'unsafe-inline'","img-src 'self' data:","font-src 'self' data:","connect-src 'self'","form-action 'self' https://checkout.stripe.com https://billing.stripe.com","frame-ancestors 'none'","base-uri 'self'","object-src 'none'"].join('; '));if(config.isHosted)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next()})

// Stripe webhook: idempotency stored relationally, no global DB snapshot.
app.post('/api/webhooks/stripe',express.raw({type:'application/json',limit:'1mb'}),async(req,res)=>{
 const s=getStripe();if(!s||!config.stripe.webhookSecret)return res.status(503).json({error:'Webhook not configured'})
 let event;try{event=s.webhooks.constructEvent(req.body,req.headers['stripe-signature'],config.stripe.webhookSecret)}catch{return res.status(400).json({error:'Invalid signature'})}
 const existing=await one('SELECT * FROM webhook_events WHERE id=$1',[event.id]);if(existing?.status==='completed')return res.json({received:true,duplicate:true})
 await sql(`INSERT INTO webhook_events(id,type,status,attempts,last_attempt_at) VALUES($1,$2,'processing',1,now()) ON CONFLICT(id) DO UPDATE SET status='processing',attempts=webhook_events.attempts+1,last_attempt_at=now(),error=NULL`,[event.id,event.type])
 try{
   const obj=event.data.object
   if(event.type.startsWith('customer.subscription.')) await applyStripeSubscription(obj)
   if(event.type==='checkout.session.completed'&&obj.subscription){const sub=await s.subscriptions.retrieve(String(obj.subscription));await applyStripeSubscription(sub,true)}
   if(event.type==='invoice.paid'||event.type==='invoice.payment_failed') await recordInvoice(obj,event.type==='invoice.paid'?'paid':'failed')
   await sql(`UPDATE webhook_events SET status='completed',completed_at=now() WHERE id=$1`,[event.id]);res.json({received:true})
 }catch(err){await sql(`UPDATE webhook_events SET status='failed',error=$2 WHERE id=$1`,[event.id,String(err?.message||err).slice(0,1000)]);res.status(500).json({error:'Processing failed'})}
})

app.use(express.json({limit:'256kb'}))

// Persistent Postgres rate limiter. Works across instances.
function rateLimit({windowMs,max,name,message='Πολλά αιτήματα. Δοκίμασε ξανά σε λίγο.',keyFn}){return async(req,res,next)=>{const rawKey=keyFn?String(keyFn(req)||'anonymous'):String(req.ip||'local');const bucket=`${name}:${sha256(rawKey).slice(0,24)}`;try{let count,ttlMs;if(config.redis.url){try{const r=await redisRateLimit(config.redis.keyPrefix+'rl:'+bucket,windowMs);count=r.count;ttlMs=r.ttlMs}catch(err){console.warn('[MELEO v5.1] Redis limiter fallback:',err.message)}}if(count==null){const row=await one(`INSERT INTO rate_limits(bucket_key,count,reset_at) VALUES($1,1,now()+($2||' milliseconds')::interval) ON CONFLICT(bucket_key) DO UPDATE SET count=CASE WHEN rate_limits.reset_at<=now() THEN 1 ELSE rate_limits.count+1 END,reset_at=CASE WHEN rate_limits.reset_at<=now() THEN now()+($2||' milliseconds')::interval ELSE rate_limits.reset_at END,updated_at=now() RETURNING count,reset_at`,[bucket,String(windowMs)]);count=row.count;ttlMs=Math.max(0,new Date(row.reset_at).getTime()-Date.now())}if(count>max){res.setHeader('Retry-After',Math.max(1,Math.ceil(ttlMs/1000)));return res.status(429).json({error:message})}next()}catch(e){next(e)}}}
const limits={global:rateLimit({windowMs:60000,max:500,name:'global'}),login:rateLimit({windowMs:900000,max:20,name:'login'}),loginAccount:rateLimit({windowMs:900000,max:10,name:'login-account',keyFn:req=>String(req.body?.email||'').trim().toLowerCase()}),admin:rateLimit({windowMs:60000,max:90,name:'admin'}),adminWrite:rateLimit({windowMs:60000,max:20,name:'admin-write'}),register:rateLimit({windowMs:3600000,max:10,name:'register'}),password:rateLimit({windowMs:3600000,max:8,name:'password'}),write:rateLimit({windowMs:60000,max:60,name:'write'}),geo:rateLimit({windowMs:60000,max:30,name:'geo'}),checkout:rateLimit({windowMs:600000,max:15,name:'checkout'}),profile:rateLimit({windowMs:60000,max:60,name:'profile'}),analytics:rateLimit({windowMs:60000,max:25,name:'analytics'})}
app.use('/api',limits.global)
app.use('/api',(req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method)||req.path.startsWith('/webhooks/'))return next();const origin=String(req.headers.origin||'');if(!origin)return next();try{if(new URL(origin).origin!==new URL(config.appUrl).origin)return res.status(403).json({error:'Μη έγκυρη προέλευση αιτήματος'})}catch{return res.status(403).json({error:'Μη έγκυρη προέλευση αιτήματος'})}next()})

async function auth(req,res,next){const raw=cookieNamed(req,SESSION_COOKIE)||String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!raw)return res.status(401).json({error:'Απαιτείται σύνδεση'});const row=await Sessions.resolve(raw);if(!row)return res.status(401).json({error:'Η συνεδρία έληξε. Συνδέσου ξανά.'});if(row.account_status==='suspended'&&row.role!=='admin')return res.status(403).json({error:'Ο λογαριασμός έχει ανασταλεί από τη MELEO.'});if(row.role==='admin'&&config.admin.bindUserAgent&&row.user_agent_hash&&row.user_agent_hash!==sha256(req.headers['user-agent']||'')){await Sessions.revoke(raw);await audit(row.user_id,'security.admin_session_ua_mismatch',{ipHash:sha256(req.ip||'')});clearSessionCookie(res);return res.status(401).json({error:'Η συνεδρία admin ακυρώθηκε για λόγους ασφαλείας.'})}req.user=publicUser(row);req.user.passwordHash=row.password_hash;req.user.stripeCustomerId=row.stripe_customer_id;req.sessionRaw=raw;next()}
const requireRole=role=>(req,res,next)=>req.user.role===role?next():res.status(403).json({error:role==='admin'?'Admin only':'Δεν επιτρέπεται για αυτόν τον τύπο λογαριασμού'})
const adminIpGuard=(req,res,next)=>{if(!config.admin.ipAllowlist.length)return next();const ip=String(req.ip||'').replace(/^::ffff:/,'');if(config.admin.ipAllowlist.includes(ip))return next();audit(req.user?.id||null,'security.admin_ip_denied',{ipHash:sha256(ip)}).catch(()=>{});return res.status(403).json({error:'Η πρόσβαση διαχειριστή δεν επιτρέπεται από αυτή τη διεύθυνση IP.'})}
function requireVerifiedEmail(req,res,next){if(config.mailEnabled&&!req.user.emailVerified)return res.status(403).json({error:'Επιβεβαίωσε πρώτα το email σου.'});next()}

async function issueSession(user,req,res){const ttl=user.role==='admin'?ADMIN_SESSION_TTL_MS:SESSION_TTL_MS;const raw=newToken();await Sessions.issue(user.id,raw,new Date(Date.now()+ttl).toISOString(),{ipHash:sha256(req.ip||''),uaHash:sha256(req.headers['user-agent']||'')});setSessionCookie(res,raw,ttl)}
async function createToken(userId,type,ttl){const raw=newToken();await sql('DELETE FROM one_time_tokens WHERE user_id=$1 AND type=$2',[userId,type]);await sql(`INSERT INTO one_time_tokens(id,user_id,type,token_hash,expires_at) VALUES($1,$2,$3,$4,now()+($5||' milliseconds')::interval)`,[id('tok'),userId,type,sha256(raw),String(ttl)]);return raw}
async function consumeToken(raw,type){return tx(async c=>{const {rows}=await c.query(`SELECT * FROM one_time_tokens WHERE token_hash=$1 AND type=$2 AND used_at IS NULL AND expires_at>now() FOR UPDATE`,[sha256(raw),type]);const r=rows[0];if(!r)return null;await c.query('UPDATE one_time_tokens SET used_at=now() WHERE id=$1',[r.id]);return r})}

const PROFILE_EDITABLE=['title','specialty','bio','city','area','region','countryCode','latitude','longitude','serviceRadiusKm','price','pricingMode','years','services','availability','languages','available','showPhone','showEmail','preferPlatformContact']
const SPECIALTIES=['Νοσηλευτική','Φυσικοθεραπεία','Διαιτολογία / Διατροφή','Εργοθεραπεία','Λογοθεραπεία','Μαιευτική φροντίδα','Ψυχολογία','Φροντίδα ηλικιωμένων','Αποκατάσταση']
function sanitizeProfilePatch(body={}){const p={};for(const k of PROFILE_EDITABLE){if(!(k in body))continue;const v=body[k];if(['services','availability','languages'].includes(k))p[k]=(Array.isArray(v)?v:String(v??'').split(',')).map(x=>str(x,80)).filter(Boolean).slice(0,30);else if(k==='price')p[k]=Math.min(5000,Math.max(0,Number(v)||0));else if(k==='years')p[k]=Math.min(70,Math.max(0,Math.round(Number(v)||0)));else if(k==='serviceRadiusKm')p[k]=Math.min(300,Math.max(1,Math.round(Number(v)||15)));else if(k==='pricingMode')p[k]=v==='from'?'from':'contact';else if(['latitude','longitude'].includes(k))p[k]=(v==null||v==='')?null:Number(v);else if(['showPhone','showEmail','preferPlatformContact'].includes(k))p[k]=Boolean(v);else if(k==='specialty')p[k]=SPECIALTIES.includes(v)?v:'';else if(k==='bio')p[k]=str(v,1500);else p[k]=str(v,120)}return p}

async function ensureDemoData(){if(!config.seedDemo)return;const c=await one('SELECT count(*)::int n FROM users');if(c.n)return;const pass=await hashPassword('demo123');await tx(async client=>{for(const u of [{id:'u_patient',role:'patient',name:'Γιώργος Demo',email:'patient@meleo.gr',phone:'6900000000'},{id:'u_nurse1',role:'professional',name:'Μαρία Κωνσταντίνου',email:'maria@meleo.gr',phone:'6901111111'},{id:'u_nurse2',role:'professional',name:'Νίκος Στεφανάκης',email:'nikos@meleo.gr',phone:'6902222222'}])await client.query(`INSERT INTO users(id,role,name,email,phone,password_hash,email_verified,accepted_terms_at) VALUES($1,$2,$3,$4,$5,$6,true,now())`,[u.id,u.role,u.name,u.email,u.phone,pass]);await client.query(`INSERT INTO professionals(id,user_id,title,specialty,verified,featured,city,area,region,latitude,longitude,service_radius_km,subscription_plan,subscription_price,subscription_status,billing_mode,onboarding_completed,onboarding_stage,subscription_since,available,bio,languages,credentials,response_time,years,price,pricing_mode,services,availability) VALUES('p1','u_nurse1','Νοσηλεύτρια','Νοσηλευτική',true,true,'Ηράκλειο','Κέντρο','Κρήτη',35.3387,25.1442,18,'premium',14.99,'active','demo',true,'approved',now(),'Σήμερα','Εξειδίκευση στη μετεγχειρητική φροντίδα.','["Ελληνικά","Αγγλικά"]','["Πτυχίο Νοσηλευτικής","BLS"]','συνήθως σε 8 λεπτά',9,25,'from','["Απλή νοσηλευτική επίσκεψη","Χορήγηση αγωγής","Περιποίηση τραύματος"]','["09:00","11:30","18:00"]'),('p2','u_nurse2','Φυσικοθεραπευτής','Φυσικοθεραπεία',true,false,'Ηράκλειο','Ατσαλένιο','Κρήτη',35.3295,25.1549,20,'basic',9.99,'active','demo',true,'approved',now(),'Αύριο','Κατ’ οίκον φυσικοθεραπεία.','["Ελληνικά","Αγγλικά"]','["Πτυχίο Φυσικοθεραπείας"]','συνήθως σε 14 λεπτά',7,30,'from','["Κατ’ οίκον φυσικοθεραπεία","Μετεγχειρητική αποκατάσταση"]','["08:30","12:00","17:00"]')`);await client.query(`INSERT INTO professional_analytics_daily(professional_id,day,impressions,profile_views,phone_clicks) VALUES('p1',current_date,183,41,12),('p2',current_date,96,24,5)`)});console.log('[MELEO v5] demo relational seed created')}
async function ensureAdmin(){const email=config.admin.email;const pass=config.admin.password||(config.isProd?'':'admin123');if(!pass)return;let u=await Users.byEmail(email);if(!u){u=await Users.create({id:'u_admin',role:'admin',name:'MELEO Admin',email,phone:'',passwordHash:await hashPassword(pass),emailVerified:true,acceptedTermsAt:now()})}else if(config.admin.password){await Users.update(u.id,{password_hash:await hashPassword(config.admin.password)})}}
await ensureDemoData();await ensureAdmin()

app.get('/api/config',(_req,res)=>res.json({env:config.env,demoAuth:config.demoAuth,demoCheckout:config.demoCheckout,paymentsEnabled:config.stripeEnabled,mailEnabled:config.mailEnabled,portalEnabled:config.stripeEnabled&&config.stripe.portalEnabled,plans:Object.values(PLANS),termsVersion:config.legal.termsVersion,emergencyNumber:config.emergencyNumber,legal:{company:config.legal.company,vatNumber:config.legal.vatNumber,address:config.legal.address,supportEmail:config.mail.supportEmail,dpoEmail:config.legal.dpoEmail}}))
app.get('/api/health',async(_req,res)=>{const counts=await one(`SELECT (SELECT count(*) FROM users)::int users,(SELECT count(*) FROM professionals)::int professionals`);res.json({ok:true,service:'MELEO API',version:APP_VERSION,instance:process.env.INSTANCE_ID||process.env.HOSTNAME||'local',env:config.env,storage:{database:'postgres-relational',documents:config.storage.driver,multiInstanceSafe:config.storage.driver==='s3',redis:Boolean(config.redis.url)},...counts})})
app.get('/api/ready',async(_req,res)=>{try{await one('SELECT 1 ok');let redis=true;if(config.redis.url){try{redis=await redisPing()}catch{redis=false}}const objectStorage=await storageReady();if((config.redis.required&&!redis)||(config.isProd&&!objectStorage))return res.status(503).json({ok:false,checks:{database:true,redis,objectStorage}});res.json({ok:true,service:'MELEO',version:APP_VERSION,instance:process.env.INSTANCE_ID||process.env.HOSTNAME||'local',checks:{database:true,redis,objectStorage,payments:config.isProd?config.stripeEnabled:true,mail:config.isProd?config.mailEnabled:true,admin2fa:config.isProd?Boolean(config.admin.totpSecret):true}})}catch{res.status(503).json({ok:false})}})
app.get('/api/metrics',async(req,res)=>{if(config.isHosted){const supplied=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!config.observability.metricsToken||supplied!==config.observability.metricsToken)return res.status(404).end()}const q=await queueStats();const pool=getPool();res.type('text/plain; version=0.0.4').send(metricsText({background_jobs_pending:q.pending,background_jobs_processing:q.processing,background_jobs_failed:q.failed,postgres_pool_total:pool.totalCount,postgres_pool_idle:pool.idleCount,postgres_pool_waiting:pool.waitingCount}))})
app.get('/api/plans',(_req,res)=>res.json(Object.values(PLANS)))

app.post('/api/auth/register',limits.register,async(req,res)=>{const role=req.body.role==='professional'?'professional':'patient',name=str(req.body.name,120),email=str(req.body.email,200).toLowerCase(),phone=str(req.body.phone,40),password=String(req.body.password||'');if(!name||!isEmail(email)||password.length<PASSWORD_MIN)return res.status(400).json({error:'Συμπλήρωσε σωστά όνομα, email και κωδικό τουλάχιστον 8 χαρακτήρων.'});if(await Users.byEmail(email))return res.status(409).json({error:'Υπάρχει ήδη λογαριασμός με αυτό το email.'});const uid=id('usr');const u=await Users.create({id:uid,role,name,email,phone,passwordHash:await hashPassword(password),emailVerified:!config.mailEnabled,acceptedTermsAt:now(),termsVersion:config.legal.termsVersion});if(role==='professional')await Professionals.createForUser(uid);if(config.mailEnabled){const t=await createToken(uid,'verify_email',24*3600000);mail.verifyEmail(email,name,`${config.appUrl}/?verify_email=${encodeURIComponent(t)}`).catch(()=>{})}await issueSession(u,req,res);await audit(uid,'auth.register',{role});res.json({token:'cookie',user:publicUser(u),professional:role==='professional'?await Professionals.byUser(uid):null})})
app.post('/api/auth/login',limits.login,limits.loginAccount,async(req,res)=>{const email=str(req.body.email,200).toLowerCase(),password=String(req.body.password||'');const u=await Users.byEmail(email);if(!u||!await verifyPassword(password,u.password_hash)){if(email===config.admin.email||u?.role==='admin')await audit(u?.id||null,'security.admin_login_failed',{ipHash:sha256(req.ip||''),uaHash:sha256(req.headers['user-agent']||'')});return res.status(401).json({error:'Λάθος email ή κωδικός.'});}if(u.account_status==='suspended'&&u.role!=='admin')return res.status(403).json({error:'Ο λογαριασμός έχει ανασταλεί.'});if(u.role==='admin'&&config.admin.totpSecret){const step=matchTotpStep(config.admin.totpSecret,req.body.totp);if(step==null){await audit(u.id,'security.admin_2fa_failed',{ipHash:sha256(req.ip||'')});return res.status(401).json({error:'Απαιτείται έγκυρος κωδικός 2FA.',requires2fa:true})}if(u.last_totp_step!=null&&Number(u.last_totp_step)>=step){await audit(u.id,'security.admin_2fa_replay',{ipHash:sha256(req.ip||'')});return res.status(401).json({error:'Ο κωδικός 2FA έχει ήδη χρησιμοποιηθεί.'})};await Users.update(u.id,{last_totp_step:step})}await Users.update(u.id,{last_login_at:now()});await issueSession(u,req,res);await audit(u.id,'auth.login',{});res.json({token:'cookie',user:publicUser(u),professional:u.role==='professional'?await Professionals.byUser(u.id):null})})
app.post('/api/auth/logout',auth,async(req,res)=>{await Sessions.revoke(req.sessionRaw);clearSessionCookie(res);res.json({ok:true})})
app.post('/api/auth/social-demo',async(req,res)=>{if(!config.demoAuth)return res.status(404).json({error:'Unavailable'});const role=req.body.role==='professional'?'professional':'patient';const email=role==='professional'?'maria@meleo.gr':'patient@meleo.gr';const u=await Users.byEmail(email);await issueSession(u,req,res);res.json({token:'cookie',user:publicUser(u),professional:role==='professional'?await Professionals.byUser(u.id):null})})
app.post('/api/auth/forgot-password',limits.password,async(req,res)=>{const u=await Users.byEmail(str(req.body.email,200).toLowerCase());if(u&&config.mailEnabled){const t=await createToken(u.id,'password_reset',3600000);mail.resetPassword(u.email,u.name,`${config.appUrl}/?reset=${encodeURIComponent(t)}`).catch(()=>{})}res.json({ok:true})})
app.post('/api/auth/reset-password',limits.password,async(req,res)=>{const password=String(req.body.password||'');if(password.length<PASSWORD_MIN)return res.status(400).json({error:'Ο κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες.'});const rec=await consumeToken(str(req.body.token,300),'password_reset');if(!rec)return res.status(400).json({error:'Ο σύνδεσμος έχει λήξει ή χρησιμοποιηθεί.'});await Users.update(rec.user_id,{password_hash:await hashPassword(password)});await Sessions.revokeUser(rec.user_id);res.json({ok:true})})
app.post('/api/auth/verify-email',async(req,res)=>{const rec=await consumeToken(str(req.body.token,300),'verify_email');if(!rec)return res.status(400).json({error:'Ο σύνδεσμος δεν είναι έγκυρος.'});await Users.update(rec.user_id,{email_verified:true});res.json({ok:true})})
app.post('/api/auth/verify-email/resend',auth,limits.password,async(req,res)=>{if(!config.mailEnabled)return res.json({ok:true});const u=await Users.byId(req.user.id);const t=await createToken(u.id,'verify_email',24*3600000);mail.verifyEmail(u.email,u.name,`${config.appUrl}/?verify_email=${encodeURIComponent(t)}`).catch(()=>{});res.json({ok:true})})

app.get('/api/me',auth,async(req,res)=>{const u=await Users.byId(req.user.id);res.json({user:publicUser(u),professional:u.role==='professional'?await Professionals.byUser(u.id):null})})
app.get('/api/me/sessions',auth,async(req,res)=>{res.json({items:await Sessions.listForUser(req.user.id,req.sessionRaw)})})
app.delete('/api/me/sessions/others',auth,limits.password,async(req,res)=>{await Sessions.revokeOthers(req.user.id,req.sessionRaw);await audit(req.user.id,'security.sessions_revoke_others',{});res.json({ok:true})})
app.put('/api/me',auth,limits.write,async(req,res)=>{const u=await Users.update(req.user.id,{name:str(req.body.name,120)||req.user.name,phone:str(req.body.phone,40)});res.json({user:publicUser(u)})})
app.post('/api/me/change-password',auth,limits.password,async(req,res)=>{const u=await Users.byId(req.user.id);if(!await verifyPassword(String(req.body.currentPassword||''),u.password_hash))return res.status(400).json({error:'Ο τρέχων κωδικός δεν είναι σωστός.'});const np=String(req.body.newPassword||'');if(np.length<PASSWORD_MIN)return res.status(400).json({error:'Ο νέος κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες.'});await Users.update(u.id,{password_hash:await hashPassword(np)});await Sessions.revokeUser(u.id);clearSessionCookie(res);res.json({ok:true})})
app.get('/api/me/export',auth,async(req,res)=>{const u=await Users.byId(req.user.id),p=u.role==='professional'?await Professionals.byUser(u.id):null,b=await Bookings.listForUser(publicUser(u),{limit:100});res.json({exportedAt:now(),user:publicUser(u),professional:p,bookings:b.items})})

app.delete('/api/me',auth,limits.password,async(req,res)=>{const u=await Users.byId(req.user.id);if(req.body.password&&!await verifyPassword(String(req.body.password),u.password_hash))return res.status(400).json({error:'Λάθος κωδικός.'});const p=u.role==='professional'?await Professionals.byUser(u.id):null;if(p?.stripeSubscriptionId&&getStripe()){try{await getStripe().subscriptions.cancel(p.stripeSubscriptionId)}catch(err){await Users.update(u.id,{deletion_pending:true,deletion_requested_at:now()});return res.status(202).json({ok:true,pending:true,message:'Η διαγραφή θα ολοκληρωθεί μόλις ακυρωθεί η συνδρομή.'})}}await Users.update(u.id,{deleted_at:now(),name:'Deleted User',phone:'',account_status:'suspended'});await Sessions.revokeUser(u.id);clearSessionCookie(res);res.json({ok:true})})

// Geocoding with persistent cache. Nominatim only in dev unless explicitly selected.
async function geocode(pathname){const key=sha256(pathname);if(config.redis.url){try{const hit=await redisGetJson(config.redis.keyPrefix+'geo:'+key);if(hit)return hit}catch(err){console.warn('[MELEO v5.1] Redis geocode cache fallback:',err.message)}}const cached=await one('SELECT payload FROM geocode_cache WHERE cache_key=$1 AND expires_at>now()',[key]);if(cached){if(config.redis.url)redisSetJson(config.redis.keyPrefix+'geo:'+key,cached.payload,86400).catch(()=>{});return cached.payload;}const provider=(process.env.GEOCODING_PROVIDER||'nominatim').toLowerCase();let url,headers={};if(provider==='mapbox'&&process.env.MAPBOX_TOKEN){const q=new URLSearchParams(pathname.split('?')[1]||'');const query=q.get('q')||'';url=`https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(query)}.json?access_token=${encodeURIComponent(process.env.MAPBOX_TOKEN)}&language=el&limit=5`}else{url=`https://nominatim.openstreetmap.org${pathname}`;headers={'User-Agent':`MELEO-Marketplace/5.0 (${config.mail.supportEmail})`,'Accept-Language':'el,en'}}const r=await fetch(url,{headers});if(!r.ok)throw new Error('Geocoding unavailable');let data=await r.json();if(provider==='mapbox'&&data.features)data=data.features.map(f=>({lat:String(f.center[1]),lon:String(f.center[0]),display_name:f.place_name,address:{city:f.context?.find(x=>x.id.startsWith('place.'))?.text||f.text,country:f.context?.find(x=>x.id.startsWith('country.'))?.text||''}}));await sql(`INSERT INTO geocode_cache(cache_key,payload,expires_at) VALUES($1,$2,now()+interval '30 days') ON CONFLICT(cache_key) DO UPDATE SET payload=$2,expires_at=now()+interval '30 days',updated_at=now()`,[key,data]);if(config.redis.url)redisSetJson(config.redis.keyPrefix+'geo:'+key,data,30*86400).catch(()=>{});return data}
app.get('/api/location/search',limits.geo,async(req,res)=>{const q=str(req.query.q,200);if(!q)return res.json([]);try{const raw=(await geocode(`/search?format=jsonv2&addressdetails=1&limit=5&q=${encodeURIComponent(q)}`)).slice(0,5);res.json(raw.map(x=>{const a=x.address||{};return {label:x.display_name||'',lat:Number(x.lat),lon:Number(x.lon),city:a.city||a.town||a.village||a.municipality||a.county||'',region:a.state||a.region||'',countryCode:String(a.country_code||'').toLowerCase(),country:a.country||''}}))}catch{res.status(503).json({error:'Η υπηρεσία τοποθεσίας δεν είναι διαθέσιμη.'})}})
app.get('/api/location/reverse',limits.geo,async(req,res)=>{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'Invalid coordinates'});try{const x=await geocode(`/reverse?format=jsonv2&addressdetails=1&lat=${lat}&lon=${lon}`),a=x.address||{};res.json({label:x.display_name||'',lat,lon,city:a.city||a.town||a.village||a.municipality||a.county||'',region:a.state||a.region||'',countryCode:String(a.country_code||'').toLowerCase(),country:a.country||''})}catch{res.status(503).json({error:'Η υπηρεσία τοποθεσίας δεν είναι διαθέσιμη.'})}})

app.post('/api/analytics/professional-event',limits.analytics,async(req,res)=>{const pid=str(req.body.professionalId,80),type=str(req.body.type,40),sid=str(req.body.sessionId,100);if(!['impression','profile_view','phone_click'].includes(type)||!pid)return res.status(400).json({error:'Invalid event'});const windowMin=type==='impression'?60:type==='profile_view'?30:5;const fp=fingerprint(pid,type,sid,sha256(req.ip||''),new Date().toISOString().slice(0,13));const accepted=await Analytics.event(pid,type,fp,windowMin);res.json({ok:true,accepted})})
app.get('/api/professional/analytics',auth,requireRole('professional'),async(req,res)=>{const p=await Professionals.byUser(req.user.id);res.json(await Analytics.summary(p.id,Math.min(365,Math.max(1,Number(req.query.days)||30))))})

app.get('/api/professionals',async(req,res)=>{const result=await Professionals.search(req.query);res.json(result)})
app.get('/api/professionals/:id',limits.profile,async(req,res)=>{const p=await Professionals.byId(req.params.id);if(!p||!p.verified||p.adminSuspended||!allowsVisibility(p))return res.status(404).json({error:'Ο επαγγελματίας δεν είναι διαθέσιμος.'});res.json({professional:p})})
app.get('/api/seo/resolve',async(req,res)=>{const specialtySlug=str(req.query.specialty,120),citySlug=str(req.query.city,120);const rows=await many(`SELECT DISTINCT specialty,city FROM professionals WHERE verified=true AND admin_suspended=false AND subscription_status='active' AND specialty<>'' AND city<>'' LIMIT 3000`);const match=rows.find(x=>slugify(x.specialty)===specialtySlug&&slugify(x.city)===citySlug);if(!match)return res.status(404).json({error:'Not found'});res.json(match)})

app.get('/api/professionals/:id/reviews',async(req,res)=>{const {page,limit,offset}=pagination(req.query,{defaultLimit:10,maxLimit:50});const items=await many(`SELECT r.id,r.rating,r.comment,r.created_at "createdAt",u.name "patientName" FROM reviews r JOIN users u ON u.id=r.patient_id WHERE r.professional_id=$1 ORDER BY r.created_at DESC LIMIT $2 OFFSET $3`,[req.params.id,limit,offset]);const c=await one('SELECT count(*)::int total FROM reviews WHERE professional_id=$1',[req.params.id]);res.json({items,page,limit,total:c.total,totalPages:Math.ceil(c.total/limit)})})

app.put('/api/professional/profile',auth,requireRole('professional'),limits.write,async(req,res)=>{const p=await Professionals.byUser(req.user.id);const patch=sanitizeProfilePatch(req.body);if(Object.keys(patch).length)await Professionals.update(p.id,patch);const updated=await Professionals.byId(p.id);if(updated.specialty&&updated.title&&updated.city&&!['pending_verification','approved'].includes(updated.onboardingStage))await Professionals.update(p.id,{onboardingStage:'verification'});res.json({professional:await Professionals.byId(p.id)})})

app.post('/api/professional/verification-document',auth,requireRole('professional'),requireVerifiedEmail,limits.write,async(req,res)=>{const p=await Professionals.byUser(req.user.id);const name=str(req.body.name,180),data=String(req.body.data||'');if(!data||data.length>12_000_000)return res.status(400).json({error:'Το αρχείο είναι κενό ή πολύ μεγάλο.'});const buf=Buffer.from(data,'base64');let detected='';if(buf.slice(0,4).toString('hex')==='25504446')detected='application/pdf';else if(buf.slice(0,3).toString('hex')==='ffd8ff')detected='image/jpeg';else if(buf.slice(0,8).toString('hex')==='89504e470d0a1a0a')detected='image/png';else if(buf.slice(0,4).toString()==='RIFF'&&buf.slice(8,12).toString()==='WEBP')detected='image/webp';if(!detected)return res.status(400).json({error:'Επιτρέπονται μόνο PDF/JPG/PNG/WEBP.'});const did=id('doc'),storageKey=verificationObjectKey(did);await putVerificationObject(storageKey,encryptFileBuffer(buf));try{await sql(`INSERT INTO verification_documents(id,professional_id,storage_key,original_name,mime_type,size_bytes) VALUES($1,$2,$3,$4,$5,$6)`,[did,p.id,storageKey,name,detected,buf.length])}catch(e){await deleteVerificationObject(storageKey).catch(()=>{});throw e}res.json({ok:true,id:did,name,mime:detected,size:buf.length,storage:config.storage.driver})})
app.get('/api/professional/verification-documents',auth,requireRole('professional'),async(req,res)=>{const p=await Professionals.byUser(req.user.id);const items=await many(`SELECT id,original_name name,mime_type mime,size_bytes size,created_at "createdAt" FROM verification_documents WHERE professional_id=$1 ORDER BY created_at DESC`,[p.id]);res.json(items)})
app.post('/api/professional/verification',auth,requireRole('professional'),requireVerifiedEmail,limits.write,async(req,res)=>{const p=await Professionals.byUser(req.user.id);if(!p.subscriptionPlan||!['active','past_due'].includes(p.subscriptionStatus))return res.status(400).json({error:'Απαιτείται πρώτα ενεργή συνδρομή.'});if(!p.specialty||!p.title||!p.city)return res.status(400).json({error:'Ολοκλήρωσε πρώτα το επαγγελματικό προφίλ.'});const rid=id('ver');await sql(`INSERT INTO verification_requests(id,professional_id,license_number,notes,status) VALUES($1,$2,$3,$4,'pending')`,[rid,p.id,str(req.body.licenseNumber,120),str(req.body.notes,1000)]);await Professionals.update(p.id,{onboardingStage:'pending_verification'});await audit(req.user.id,'verification.submit',{professionalId:p.id});res.json({ok:true,request:{id:rid,status:'pending'}})})

async function ensureStripeCustomer(u){if(u.stripe_customer_id)return u.stripe_customer_id;const s=getStripe();const c=await s.customers.create({email:u.email,name:u.name,phone:u.phone||undefined,metadata:{meleoUserId:u.id}});await Users.update(u.id,{stripe_customer_id:c.id});return c.id}
async function applyStripeSubscription(sub,notifyUser=false){const uid=sub.metadata?.meleoUserId;let p=uid?await Professionals.byUser(uid):null;if(!p&&sub.id){const r=await one('SELECT user_id FROM professionals WHERE stripe_subscription_id=$1',[sub.id]);if(r)p=await Professionals.byUser(r.user_id)}if(!p)return null;let plan=isPlan(sub.metadata?.plan)?sub.metadata.plan:'basic';const amount=sub.items?.data?.[0]?.price?.unit_amount;if(amount===1499)plan='premium';const status=mapStripeStatus(sub.status),period=sub.items?.data?.[0]?.current_period_end??sub.current_period_end;const patch={subscriptionPlan:plan,subscriptionPrice:PLANS[plan].price,subscriptionStatus:status,billingMode:'stripe',stripeSubscriptionId:sub.id,currentPeriodEnd:period?new Date(period*1000).toISOString():null,cancelAtPeriodEnd:!!sub.cancel_at_period_end,featured:plan==='premium'&&status==='active'};if(status==='past_due'&&!p.pastDueSince)patch.pastDueSince=now();if(status==='active'){patch.pastDueSince=null;if(!p.subscriptionSince)patch.subscriptionSince=now();if(!p.onboardingStage||p.onboardingStage==='plan')patch.onboardingStage='profile'}p=await Professionals.update(p.id,patch);await sql(`INSERT INTO subscriptions(id,professional_id,stripe_subscription_id,plan,price,status,stripe_status,billing_mode,started_at,current_period_end,cancel_at_period_end) VALUES($1,$2,$3,$4,$5,$6,$7,'stripe',now(),$8,$9) ON CONFLICT(stripe_subscription_id) DO UPDATE SET plan=$4,price=$5,status=$6,stripe_status=$7,current_period_end=$8,cancel_at_period_end=$9,updated_at=now()`,[id('sub'),p.id,sub.id,plan,PLANS[plan].price,status,sub.status,p.currentPeriodEnd,p.cancelAtPeriodEnd]);if(notifyUser&&status==='active'){await Notifications.create(p.userId,'subscription',`Η συνδρομή ${plan.toUpperCase()} είναι ενεργή`,`${PLANS[plan].price.toFixed(2)}€/μήνα`);const u=await Users.byId(p.userId);mail.subscriptionActive(u.email,u.name,plan.toUpperCase(),PLANS[plan].price.toFixed(2)).catch(()=>{})}return p}
async function recordInvoice(inv,status){let p=null;const sid=inv.subscription||inv.parent?.subscription_details?.subscription;if(sid){const r=await one('SELECT user_id FROM professionals WHERE stripe_subscription_id=$1',[String(sid)]);if(r)p=await Professionals.byUser(r.user_id)}await sql(`INSERT INTO payments(id,professional_id,invoice_id,amount,currency,status,hosted_invoice_url) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(invoice_id,status) DO NOTHING`,[id('pay'),p?.id||null,inv.id,(inv.amount_paid??inv.amount_due??0)/100,(inv.currency||'eur').toUpperCase(),status,inv.hosted_invoice_url||null]);if(status==='failed'&&p)await Notifications.create(p.userId,'billing','Αποτυχία πληρωμής συνδρομής','Ενημέρωσε τον τρόπο πληρωμής για να παραμείνει ενεργό το προφίλ σου.')}
app.get('/api/professional/subscription',auth,requireRole('professional'),async(req,res)=>{
 const p=await Professionals.byUser(req.user.id);if(!p)return res.status(404).json({error:'Δεν βρέθηκε επαγγελματικό προφίλ'});
 const invoices=await many(`SELECT id,invoice_id "invoiceId",amount,currency,status,provider,hosted_invoice_url "hostedInvoiceUrl",created_at "createdAt" FROM payments WHERE professional_id=$1 ORDER BY created_at DESC LIMIT 24`,[p.id]);
 res.json({plan:p.subscriptionPlan,price:p.subscriptionPrice,status:p.subscriptionStatus,stripeStatus:p.stripeStatus||null,billingMode:p.billingMode,currentPeriodEnd:p.currentPeriodEnd,cancelAtPeriodEnd:Boolean(p.cancelAtPeriodEnd),portalAvailable:Boolean(getStripe()&&config.stripe.portalEnabled&&p.stripeSubscriptionId),invoices:invoices.map(x=>({...x,amount:Number(x.amount||0)}))})
})
app.post('/api/professional/subscription/checkout',auth,requireRole('professional'),limits.checkout,async(req,res)=>{const plan=str(req.body.plan,20);if(!isPlan(plan))return res.status(400).json({error:'Μη έγκυρο πακέτο.'});const p=await Professionals.byUser(req.user.id);if(config.demoCheckout){await Professionals.update(p.id,{subscriptionPlan:plan,subscriptionPrice:PLANS[plan].price,subscriptionStatus:'active',billingMode:'demo',subscriptionSince:p.subscriptionSince||now(),featured:plan==='premium',onboardingStage:'profile'});return res.json({mode:'demo',demo:true,professional:await Professionals.byId(p.id)})}const s=getStripe();if(!s)return res.status(503).json({error:'Οι πληρωμές δεν έχουν ρυθμιστεί.'});if(p.stripeSubscriptionId&&allowsVisibility(p)){const sub=await s.subscriptions.retrieve(p.stripeSubscriptionId);const item=sub.items.data[0];const configured=priceIdFor(plan);const updated=await s.subscriptions.update(sub.id,{items:[{id:item.id,...(configured?{price:configured}:{price_data:lineItemFor(plan).price_data})}],proration_behavior:'create_prorations',cancel_at_period_end:false,metadata:{...sub.metadata,plan}});await applyStripeSubscription(updated);return res.json({changed:true,professional:await Professionals.byId(p.id)})}const u=await Users.byEmail(req.user.email),customer=await ensureStripeCustomer(u);const session=await s.checkout.sessions.create({mode:'subscription',customer,line_items:[lineItemFor(plan)],payment_method_types:['card'],locale:'el',allow_promotion_codes:true,billing_address_collection:'required',tax_id_collection:config.stripe.collectTaxId?{enabled:true}:undefined,automatic_tax:config.stripe.automaticTax?{enabled:true}:undefined,client_reference_id:u.id,subscription_data:{metadata:{plan,meleoUserId:u.id,meleoProfessionalId:p.id}},metadata:{plan,meleoUserId:u.id,meleoProfessionalId:p.id},success_url:`${config.appUrl}/?checkout=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${config.appUrl}/?checkout=cancel`});res.json({mode:'stripe',url:session.url,sessionId:session.id})})
app.post('/api/professional/subscription/sync',auth,requireRole('professional'),async(req,res)=>{const s=getStripe();if(!s)return res.status(503).json({error:'Stripe unavailable'});if(req.body.sessionId){const session=await s.checkout.sessions.retrieve(str(req.body.sessionId,300));if(session.client_reference_id&&session.client_reference_id!==req.user.id)return res.status(403).json({error:'Invalid checkout session'});if(session.subscription){const sub=await s.subscriptions.retrieve(String(session.subscription));await applyStripeSubscription(sub,true)}}res.json({professional:await Professionals.byUser(req.user.id)})})
app.post('/api/professional/subscription/portal',auth,requireRole('professional'),async(req,res)=>{const s=getStripe();if(!s)return res.status(503).json({error:'Stripe unavailable'});const u=await Users.byEmail(req.user.email),customer=await ensureStripeCustomer(u);const session=await s.billingPortal.sessions.create({customer,return_url:`${config.appUrl}/?billing=return`,locale:'el'});res.json({url:session.url})})
app.post('/api/professional/subscription/cancel',auth,requireRole('professional'),async(req,res)=>{const p=await Professionals.byUser(req.user.id);if(config.demoCheckout){await Professionals.update(p.id,{subscriptionStatus:'cancelled',featured:false});return res.json({professional:await Professionals.byId(p.id)})}const sub=await getStripe().subscriptions.update(p.stripeSubscriptionId,{cancel_at_period_end:true});await applyStripeSubscription(sub);res.json({professional:await Professionals.byId(p.id)})})
app.post('/api/professional/subscription/resume',auth,requireRole('professional'),async(req,res)=>{const p=await Professionals.byUser(req.user.id);if(config.demoCheckout){await Professionals.update(p.id,{subscriptionStatus:'active',featured:p.subscriptionPlan==='premium'});return res.json({professional:await Professionals.byId(p.id)})}const sub=await getStripe().subscriptions.update(p.stripeSubscriptionId,{cancel_at_period_end:false});await applyStripeSubscription(sub);res.json({professional:await Professionals.byId(p.id)})})

app.post('/api/bookings',auth,requireRole('patient'),requireVerifiedEmail,limits.write,async(req,res)=>{const pid=str(req.body.professionalId,80),service=str(req.body.service,160),date=str(req.body.date,20),time=str(req.body.time,10);if(!pid||!service||!isDate(date)||!isTime(time))return res.status(400).json({error:'Συμπλήρωσε υπηρεσία, ημερομηνία και ώρα.'});const p=await Professionals.byId(pid);if(!p||!p.verified||!allowsVisibility(p))return res.status(404).json({error:'Ο επαγγελματίας δεν είναι διαθέσιμος.'});const bid=id('bkg');const b=await Bookings.create({id:bid,patientId:req.user.id,professionalId:pid,service,date,time,address:str(req.body.address,300),notes:str(req.body.notes,3000),repeat:str(req.body.repeat,120)||'Μία φορά',price:p.price});await Notifications.create(p.userId,'booking','Νέο αίτημα επίσκεψης',`${req.user.name} · ${service}`);await audit(req.user.id,'booking.create',{bookingId:bid,professionalId:pid});res.json({booking:b})})
app.get('/api/bookings',auth,async(req,res)=>res.json(await Bookings.listForUser(req.user,req.query)))
app.patch('/api/bookings/:id/status',auth,limits.write,async(req,res)=>{const b=await Bookings.byId(req.params.id);if(!b)return res.status(404).json({error:'Not found'});const p=await Professionals.byId(b.professionalId);if(!canEditBooking(req.user,b,p))return res.status(403).json({error:'Δεν επιτρέπεται.'});const status=str(req.body.status,30);if(!['pending','clarification','quoted','accepted','completed','cancelled'].includes(status))return res.status(400).json({error:'Invalid status'});const updated=await Bookings.update(b.id,{status});await Notifications.create(req.user.role==='professional'?b.patientId:p.userId,'booking',`Ενημέρωση κράτησης: ${status}`,b.service);res.json({booking:updated})})
app.post('/api/bookings/:id/clarification',auth,requireRole('professional'),limits.write,async(req,res)=>{const b=await Bookings.byId(req.params.id),p=await Professionals.byId(b?.professionalId);if(!b||p.userId!==req.user.id)return res.status(404).json({error:'Not found'});const text=str(req.body.text||req.body.question,1500);await Bookings.update(b.id,{status:'clarification'});const updated=await Bookings.addMessage(b,req.user,text,'clarification');await Notifications.create(b.patientId,'message','Ο επαγγελματίας ζητά διευκρινίσεις',text.slice(0,180));res.json({booking:updated})})
app.post('/api/bookings/:id/message',auth,limits.write,async(req,res)=>{const b=await Bookings.byId(req.params.id);if(!b)return res.status(404).json({error:'Not found'});const p=await Professionals.byId(b.professionalId);if(!canViewBooking(req.user,b,p))return res.status(403).json({error:'Δεν επιτρέπεται.'});const text=str(req.body.text,1500);const updated=await Bookings.addMessage(b,req.user,text);await Notifications.create(req.user.id===b.patientId?p.userId:b.patientId,'message','Νέο μήνυμα MELEO',text.slice(0,180));res.json({booking:updated})})
app.post('/api/bookings/:id/quote',auth,requireRole('professional'),limits.write,async(req,res)=>{const b=await Bookings.byId(req.params.id),p=await Professionals.byId(b?.professionalId);if(!b||p.userId!==req.user.id)return res.status(404).json({error:'Not found'});const price=Math.max(0,Math.min(5000,Number(req.body.price??req.body.amount)||0));if(!price)return res.status(400).json({error:'Δώσε τελικό κόστος.'});await Bookings.update(b.id,{status:'quoted',proposedPrice:price});if(req.body.note||req.body.message)await Bookings.addMessage(b,req.user,str(req.body.note||req.body.message,1000),'quote');await Notifications.create(b.patientId,'quote','Νέα πρόταση τελικού κόστους',`${price.toFixed(2)}€`);res.json({booking:await Bookings.byId(b.id)})})
app.post('/api/bookings/:id/quote-decision',auth,requireRole('patient'),limits.write,async(req,res)=>{const b=await Bookings.byId(req.params.id);if(!b||b.patientId!==req.user.id)return res.status(404).json({error:'Not found'});const accept=Boolean(req.body.accept);const updated=await Bookings.update(b.id,accept?{status:'accepted',agreedPrice:b.proposedPrice}:{status:'clarification'});const p=await Professionals.byId(b.professionalId);await Notifications.create(p.userId,'quote',accept?'Η πρόταση κόστους έγινε αποδεκτή':'Η πρόταση χρειάζεται νέα συζήτηση',b.service);res.json({booking:updated})})
app.post('/api/bookings/:id/review',auth,requireRole('patient'),limits.write,async(req,res)=>{const b=await Bookings.byId(req.params.id);if(!b||!canReviewBooking(req.user,b))return res.status(400).json({error:'Αξιολόγηση επιτρέπεται μόνο μετά από ολοκληρωμένη επίσκεψη.'});const rating=Math.max(1,Math.min(5,Math.round(Number(req.body.rating)||0))),comment=str(req.body.comment,1000);try{await tx(async c=>{await c.query(`INSERT INTO reviews(id,booking_id,patient_id,professional_id,rating,comment) VALUES($1,$2,$3,$4,$5,$6)`,[id('rev'),b.id,req.user.id,b.professionalId,rating,comment]);await c.query(`UPDATE professionals SET reviews_count=(SELECT count(*) FROM reviews WHERE professional_id=$1),rating=(SELECT coalesce(avg(rating),0) FROM reviews WHERE professional_id=$1),updated_at=now() WHERE id=$1`,[b.professionalId])})}catch(err){if(err.code==='23505')return res.status(409).json({error:'Η επίσκεψη έχει ήδη αξιολογηθεί.'});throw err}const p=await Professionals.byId(b.professionalId);await Notifications.create(p.userId,'review','Νέα αξιολόγηση',`${rating}/5 ⭐`);res.json({ok:true})})

app.get('/api/notifications',auth,async(req,res)=>res.json(await Notifications.list(req.user.id,req.query)))
app.patch('/api/notifications/:id/read',auth,async(req,res)=>{await Notifications.read(req.params.id,req.user.id);res.json({ok:true})})
app.post('/api/favorites/:professionalId',auth,requireRole('patient'),limits.write,async(req,res)=>{const pid=req.params.professionalId;const existing=await one('SELECT id FROM favorites WHERE user_id=$1 AND professional_id=$2',[req.user.id,pid]);if(existing){await sql('DELETE FROM favorites WHERE id=$1',[existing.id]);return res.json({favorite:false})}await sql('INSERT INTO favorites(id,user_id,professional_id) VALUES($1,$2,$3)',[id('fav'),req.user.id,pid]);res.json({favorite:true})})
app.get('/api/favorites',auth,async(req,res)=>{const rows=await many('SELECT professional_id FROM favorites WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json(rows.map(x=>x.professional_id))})
app.post('/api/reports',auth,limits.write,async(req,res)=>{const rid=id('rpt');await sql(`INSERT INTO reports(id,reporter_user_id,target_type,target_id,reason,details) VALUES($1,$2,$3,$4,$5,$6)`,[rid,req.user.id,str(req.body.targetType,40),str(req.body.targetId,80),str(req.body.reason,200),str(req.body.details,1500)]);res.json({ok:true,id:rid})})

// Multi-instance SSE via Postgres LISTEN/NOTIFY + persisted live_events.
const liveClients=new Map();const listener=await getPool().connect();await listener.query('LISTEN meleo_live');listener.on('notification',msg=>{let meta;try{meta=JSON.parse(msg.payload||'{}')}catch{return}const uid=meta.userId,clients=liveClients.get(uid);if(!clients?.size)return;one('SELECT payload FROM live_events WHERE id=$1 AND user_id=$2',[meta.eventId,uid]).then(e=>{if(!e)return;for(const r of [...clients])try{r.write(`event: meleo\ndata: ${JSON.stringify(e.payload)}\n\n`)}catch{clients.delete(r)}}).catch(()=>{})})
app.get('/api/live',auth,async(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders?.();const set=liveClients.get(req.user.id)||new Set();set.add(res);liveClients.set(req.user.id,set);res.write(`event: ready\ndata: {}\n\n`);const ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},25000);req.on('close',()=>{clearInterval(ping);set.delete(res);if(!set.size)liveClients.delete(req.user.id)})})

app.get('/api/bookings/:id/calendar.ics',auth,async(req,res)=>{const b=await Bookings.byId(req.params.id);if(!b)return res.status(404).end();const p=await Professionals.byId(b.professionalId);if(!canViewBooking(req.user,b,p))return res.status(403).end();const start=`${b.date.replaceAll('-','')}T${b.time.replace(':','')}00`;const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//MELEO//Booking//EL\r\nBEGIN:VEVENT\r\nUID:${b.id}@meleo.gr\r\nDTSTART:${start}\r\nSUMMARY:MELEO · ${b.service}\r\nLOCATION:${String(b.address||'').replace(/\n/g,' ')}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;res.setHeader('Content-Type','text/calendar; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="meleo-${b.id}.ics"`);res.send(ics)})

app.get('/api/support/tickets',auth,async(req,res)=>{const {page,limit,offset}=pagination(req.query,{defaultLimit:20,maxLimit:100});const where=req.user.role==='admin'?'true':'t.user_id=$1',params=req.user.role==='admin'?[]:[req.user.id];const ids=await many(`SELECT t.id FROM support_tickets t WHERE ${where} ORDER BY updated_at DESC LIMIT $${params.length+1} OFFSET $${params.length+2}`,[...params,limit,offset]);const items=[];for(const x of ids){const t=await one(`SELECT t.*,u.name user_name,u.email user_email FROM support_tickets t JOIN users u ON u.id=t.user_id WHERE t.id=$1`,[x.id]);t.messages=await many(`SELECT m.id,m.sender_role "fromRole",u.name "fromName",m.body text,m.created_at "createdAt" FROM support_messages m JOIN users u ON u.id=m.sender_user_id WHERE ticket_id=$1 ORDER BY m.created_at`,[x.id]);items.push({id:t.id,userId:t.user_id,userName:t.user_name,userEmail:t.user_email,subject:t.subject,category:t.category,status:t.status,createdAt:t.created_at,updatedAt:t.updated_at,messages:t.messages})}res.json({items,page,limit})})
app.post('/api/support/tickets',auth,limits.write,async(req,res)=>{const tid=id('tic'),subject=str(req.body.subject,160),text=str(req.body.text,2000);if(!subject||!text)return res.status(400).json({error:'Συμπλήρωσε θέμα και μήνυμα.'});await tx(async c=>{await c.query(`INSERT INTO support_tickets(id,user_id,subject,category) VALUES($1,$2,$3,$4)`,[tid,req.user.id,subject,str(req.body.category,40)||'general']);await c.query(`INSERT INTO support_messages(id,ticket_id,sender_user_id,sender_role,body) VALUES($1,$2,$3,$4,$5)`,[id('tmsg'),tid,req.user.id,req.user.role,text])});res.json({ok:true,id:tid})})
app.post('/api/support/tickets/:id/message',auth,limits.write,async(req,res)=>{const t=await one('SELECT * FROM support_tickets WHERE id=$1',[req.params.id]);if(!t||(req.user.role!=='admin'&&t.user_id!==req.user.id))return res.status(404).json({error:'Not found'});const text=str(req.body.text,2000);await sql(`INSERT INTO support_messages(id,ticket_id,sender_user_id,sender_role,body) VALUES($1,$2,$3,$4,$5)`,[id('tmsg'),t.id,req.user.id,req.user.role,text]);await sql('UPDATE support_tickets SET updated_at=now() WHERE id=$1',[t.id]);await Notifications.create(req.user.role==='admin'?t.user_id:req.user.id,'support','Νέα απάντηση υποστήριξης',text.slice(0,180));res.json({ok:true})})
app.patch('/api/support/tickets/:id',auth,requireRole('admin'),limits.write,async(req,res)=>{const status=['open','pending','closed'].includes(req.body.status)?req.body.status:'open';await sql('UPDATE support_tickets SET status=$1,updated_at=now() WHERE id=$2',[status,req.params.id]);res.json({ok:true})})

app.use('/api/admin',auth,requireRole('admin'),adminIpGuard,limits.admin)
app.use('/api/admin',(req,res,next)=>['GET','HEAD','OPTIONS'].includes(req.method)?next():limits.adminWrite(req,res,next))
app.get('/api/admin/stats',async(_req,res)=>res.json(await Admin.stats()))
app.get('/api/admin/members',async(req,res)=>{const {page,limit,offset}=pagination(req.query,{defaultLimit:30,maxLimit:100});const q=str(req.query.q,100),role=str(req.query.role,30);const where=["u.deleted_at IS NULL","u.role<>'admin'"],vals=[];let i=1;if(q){where.push(`(u.name ILIKE $${i} OR u.email ILIKE $${i})`);vals.push(`%${q}%`);i++}if(role){where.push(`u.role=$${i++}`);vals.push(role)}vals.push(limit,offset);const rows=await many(`SELECT u.id,u.name,u.email,u.phone,u.role,u.email_verified "emailVerified",u.account_status "accountStatus",u.suspended_at "suspendedAt",u.suspension_reason "suspensionReason",u.deletion_pending "deletionPending",u.last_login_at "lastLoginAt",u.created_at "createdAt",p.id "professionalId",p.specialty,p.verified,p.featured,p.rating,p.reviews_count reviews,p.city,p.subscription_plan "subscriptionPlan",p.subscription_status "subscriptionStatus",p.subscription_price "subscriptionPrice",p.billing_mode "billingMode",p.current_period_end "currentPeriodEnd",p.onboarding_stage "onboardingStage",p.onboarding_completed "onboardingCompleted",v.id "verificationRequestId",v.status "verificationStatus" FROM users u LEFT JOIN professionals p ON p.user_id=u.id LEFT JOIN LATERAL (SELECT id,status FROM verification_requests vr WHERE vr.professional_id=p.id ORDER BY submitted_at DESC LIMIT 1) v ON true WHERE ${where.join(' AND ')} ORDER BY u.created_at DESC LIMIT $${i++} OFFSET $${i}`,[...vals]);const items=rows.map(m=>{let lifecycleStatus='';if(m.deletionPending)lifecycleStatus='deletion_pending';else if(m.role==='professional'){if(m.verified)lifecycleStatus='approved';else if(m.verificationStatus==='pending')lifecycleStatus='pending_verification';else if(m.verificationStatus==='rejected')lifecycleStatus='verification_rejected';else if(!['active','past_due'].includes(m.subscriptionStatus||''))lifecycleStatus='awaiting_subscription';else if(!m.specialty||!m.city)lifecycleStatus='profile_incomplete';else lifecycleStatus='verification_required'}return {...m,lifecycleStatus,subscriptionPrice:Number(m.subscriptionPrice||0),rating:Number(m.rating||0),reviews:Number(m.reviews||0)}});const c=await one(`SELECT count(*)::int total FROM users u WHERE u.deleted_at IS NULL AND u.role<>'admin'`);res.json({items,page,limit,total:c.total,totalPages:Math.ceil(c.total/limit)})})

app.patch('/api/admin/members/:id/action',limits.write,async(req,res)=>{const u=await Users.byId(req.params.id);if(!u)return res.status(404).json({error:'Not found'});const p=u.role==='professional'?await Professionals.byUser(u.id):null,action=str(req.body.action,40),reason=str(req.body.reason,500);if(action==='suspend'){await Users.update(u.id,{account_status:'suspended',suspended_at:now(),suspension_reason:reason});await Sessions.revokeUser(u.id)}else if(action==='reactivate')await Users.update(u.id,{account_status:'active',suspended_at:null,suspension_reason:''});else if(action==='verify'&&p)await Professionals.update(p.id,{verified:true,onboardingStage:'approved',onboardingCompleted:true});else if(action==='unverify'&&p)await Professionals.update(p.id,{verified:false,onboardingStage:'verification'});else if(action==='feature'&&p&&p.subscriptionPlan==='premium')await Professionals.update(p.id,{featured:true});else if(action==='unfeature'&&p)await Professionals.update(p.id,{featured:false});else return res.status(400).json({error:'Μη έγκυρη ενέργεια.'});await audit(req.user.id,`admin.member.${action}`,{targetUserId:u.id,reason});res.json({ok:true})})
app.get('/api/admin/audit',async(req,res)=>{const {page,limit,offset}=pagination(req.query,{defaultLimit:50,maxLimit:200});const items=await many(`SELECT a.id,a.actor_id "actorId",u.name "actorName",u.email "actorEmail",a.action,a.meta,a.created_at at FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({items,page,limit})})
app.get('/api/admin/insights',async(_req,res)=>{
 const topPros=await many(`SELECT p.id,u.name,p.specialty,p.subscription_plan plan,p.verified,p.rating,p.reviews_count reviews,count(b.id)::int requests,count(b.id) FILTER(WHERE b.status='completed')::int completed,coalesce(sum(a.profile_views),0)::int "profileViews",coalesce(sum(a.impressions),0)::int impressions FROM professionals p JOIN users u ON u.id=p.user_id LEFT JOIN bookings b ON b.professional_id=p.id LEFT JOIN professional_analytics_daily a ON a.professional_id=p.id AND a.day>=current_date-30 GROUP BY p.id,u.name ORDER BY completed DESC,requests DESC LIMIT 10`);
 const signupByRole=await many(`SELECT role,count(*)::int count,count(*) FILTER(WHERE created_at>=now()-interval '30 days')::int new30 FROM users WHERE deleted_at IS NULL AND role IN ('patient','professional') GROUP BY role`);
 const bookingStatus=await many(`SELECT status name,count(*)::int count FROM bookings GROUP BY status ORDER BY count DESC`);
 const reviewDist=await many(`SELECT gs stars,coalesce(count(r.id),0)::int count FROM generate_series(5,1,-1) gs LEFT JOIN reviews r ON r.rating=gs GROUP BY gs ORDER BY gs DESC`);
 const x=await one(`SELECT (SELECT count(*) FROM users WHERE deleted_at IS NULL AND created_at>=now()-interval '7 days')::int "newUsers7",(SELECT count(*) FROM users WHERE deleted_at IS NULL AND created_at>=now()-interval '30 days')::int "newUsers30",(SELECT count(*) FROM bookings WHERE created_at>=now()-interval '7 days')::int "newBookings7",(SELECT count(*) FROM bookings WHERE created_at>=now()-interval '30 days')::int "newBookings30"`);
 res.json({topPros,signupByRole,bookingStatus,reviewDist,...x})
})

app.get('/api/admin/bookings',async(req,res)=>res.json(await Bookings.listForUser({id:req.user.id,role:'admin'},req.query)))
app.get('/api/admin/subscriptions',async(req,res)=>{const subscriptions=await many(`SELECT s.id,s.professional_id "professionalId",s.stripe_subscription_id "stripeSubscriptionId",s.plan,s.price,s.status,s.stripe_status "stripeStatus",s.billing_mode "billingMode",s.started_at "startedAt",s.current_period_end "currentPeriodEnd",s.cancel_at_period_end "cancelAtPeriodEnd",s.updated_at "updatedAt",u.name "professionalName",u.email FROM subscriptions s JOIN professionals p ON p.id=s.professional_id JOIN users u ON u.id=p.user_id ORDER BY s.updated_at DESC LIMIT 200`);const payments=await many(`SELECT id,professional_id "professionalId",invoice_id "invoiceId",amount,currency,status,provider,hosted_invoice_url "hostedInvoiceUrl",created_at "createdAt" FROM payments ORDER BY created_at DESC LIMIT 200`);res.json({subscriptions:subscriptions.map(x=>({...x,price:Number(x.price||0)})),payments:payments.map(x=>({...x,amount:Number(x.amount||0)}))})})

app.get('/api/admin/verifications',async(req,res)=>{const {page,limit,offset}=pagination(req.query,{defaultLimit:30,maxLimit:100});const rows=await many(`SELECT v.id,v.professional_id "professionalId",v.license_number "licenseNumber",v.notes,v.status,v.admin_note "adminNote",v.submitted_at "createdAt",u.name,u.email,u.phone,p.specialty,p.subscription_plan "subscriptionPlan",p.subscription_status "subscriptionStatus",p.city FROM verification_requests v JOIN professionals p ON p.id=v.professional_id JOIN users u ON u.id=p.user_id ORDER BY v.submitted_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);const items=[];for(const v of rows){const docs=await many(`SELECT id,original_name name,mime_type mime,size_bytes size,created_at "createdAt" FROM verification_documents WHERE professional_id=$1 ORDER BY created_at DESC`,[v.professionalId]);items.push({...v,documents:docs,documentCount:docs.length})}const c=await one('SELECT count(*)::int total FROM verification_requests');res.json({items,page,limit,total:c.total,totalPages:Math.ceil(c.total/limit)})})

app.get('/api/admin/verification-documents/:id',async(req,res)=>{const d=await one('SELECT * FROM verification_documents WHERE id=$1',[req.params.id]);if(!d)return res.status(404).end();try{const encrypted=await getVerificationObject(d.storage_key||`${d.id}.bin`);res.setHeader('Content-Type',d.mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(d.original_name)}`);res.setHeader('Cache-Control','no-store, private');res.end(decryptFileBuffer(encrypted))}catch(e){if(e?.code==='ENOENT'||e?.status===404)return res.status(404).end();throw e}})
app.post('/api/admin/verification-documents/:id/access',limits.write,async(req,res)=>{const d=await one('SELECT id FROM verification_documents WHERE id=$1',[req.params.id]);if(!d)return res.status(404).end();const expires=Date.now()+config.storage.signedUrlTtlSeconds*1000;const sig=createTemporaryDocumentSignature(d.id,expires);res.json({url:`/api/admin/verification-documents/${encodeURIComponent(d.id)}/signed?expires=${expires}&sig=${encodeURIComponent(sig)}`,expiresAt:new Date(expires).toISOString()})})
app.get('/api/admin/verification-documents/:id/signed',async(req,res)=>{if(!verifyTemporaryDocumentSignature(req.params.id,req.query.expires,req.query.sig))return res.status(403).json({error:'Ο προσωρινός σύνδεσμος έληξε ή δεν είναι έγκυρος.'});const d=await one('SELECT * FROM verification_documents WHERE id=$1',[req.params.id]);if(!d)return res.status(404).end();try{const encrypted=await getVerificationObject(d.storage_key||`${d.id}.bin`);res.setHeader('Content-Type',d.mime_type);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(d.original_name)}`);res.setHeader('Cache-Control','no-store, private');res.end(decryptFileBuffer(encrypted))}catch(e){if(e?.code==='ENOENT'||e?.status===404)return res.status(404).end();throw e}})
app.patch('/api/admin/verifications/:id',async(req,res)=>{const v=await one('SELECT * FROM verification_requests WHERE id=$1',[req.params.id]);if(!v)return res.status(404).json({error:'Not found'});const status=req.body.status==='approved'?'approved':'rejected',note=str(req.body.note||req.body.adminNote,1000);await tx(async c=>{await c.query(`UPDATE verification_requests SET status=$1,admin_note=$2,reviewed_by=$3,reviewed_at=now() WHERE id=$4`,[status,note,req.user.id,v.id]);await c.query(`UPDATE professionals SET verified=$1,onboarding_stage=$2,onboarding_completed=$1,updated_at=now() WHERE id=$3`,[status==='approved',status==='approved'?'approved':'verification_rejected',v.professional_id])});await audit(req.user.id,`verification.${status}`,{requestId:v.id,professionalId:v.professional_id});res.json({ok:true})})
app.post('/api/admin/professionals/:id/sync-subscription',async(req,res)=>{const p=await Professionals.byId(req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(!p.stripeSubscriptionId||!getStripe())return res.status(400).json({error:'Δεν υπάρχει Stripe subscription.'});const sub=await getStripe().subscriptions.retrieve(p.stripeSubscriptionId);const updated=await applyStripeSubscription(sub);await audit(req.user.id,'admin.subscription.sync',{professionalId:p.id});res.json({professional:updated})})

app.get('/api/admin/reports',async(req,res)=>{const {page,limit,offset}=pagination(req.query,{defaultLimit:30,maxLimit:100});const items=await many(`SELECT r.*,u.name reporter_name,u.email reporter_email FROM reports r JOIN users u ON u.id=r.reporter_user_id ORDER BY created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({items,page,limit})})
app.patch('/api/admin/reports/:id',async(req,res)=>{await sql('UPDATE reports SET status=$1,updated_at=now() WHERE id=$2',[str(req.body.status,40)||'closed',req.params.id]);res.json({ok:true})})

// SEO + static build support.
function slugify(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\u0370-\u03ff]+/g,'-').replace(/^-+|-+$/g,'')}
function htmlEscape(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function injectSeo(html,{title,description,canonical,body='',jsonLd=null}){
  let out=html.replace(/<title>.*?<\/title>/i,`<title>${htmlEscape(title)}</title>`)
  const meta=`<meta name="description" content="${htmlEscape(description)}"><link rel="canonical" href="${htmlEscape(canonical)}"><meta property="og:title" content="${htmlEscape(title)}"><meta property="og:description" content="${htmlEscape(description)}"><meta property="og:url" content="${htmlEscape(canonical)}"><meta property="og:type" content="website">${jsonLd?`<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g,'\\u003c')}</script>`:''}`
  out=out.replace('</head>',`${meta}</head>`)
  if(body)out=out.replace('<div id="root"></div>',`<div id="root"><main class="seo-prerender">${body}</main></div>`)
  return out
}
const dist=path.join(root,'dist')
if(config.isHosted&&fs.existsSync(dist)){
 const baseHtml=()=>fs.readFileSync(path.join(dist,'index.html'),'utf8')
 app.get('/robots.txt',(_req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nSitemap: ${config.appUrl}/sitemap.xml\n`))
 app.get('/sitemap.xml',async(_req,res)=>{
   const pros=await many(`SELECT p.id FROM professionals p JOIN users u ON u.id=p.user_id WHERE p.verified=true AND p.admin_suspended=false AND p.subscription_status='active' AND u.deleted_at IS NULL`)
   const combos=await many(`SELECT DISTINCT specialty,city FROM professionals WHERE verified=true AND admin_suspended=false AND subscription_status='active' AND specialty<>'' AND city<>'' LIMIT 1000`)
   const urls=[`${config.appUrl}/`,`${config.appUrl}/search`,...pros.map(p=>`${config.appUrl}/professionals/${p.id}`),...combos.map(x=>`${config.appUrl}/care/${encodeURIComponent(slugify(x.specialty))}/${encodeURIComponent(slugify(x.city))}`)]
   res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${htmlEscape(u)}</loc></url>`).join('')}</urlset>`)
 })
 app.get('/professionals/:id',async(req,res,next)=>{
   const p=await Professionals.byId(req.params.id);if(!p||!p.verified||p.adminSuspended||!allowsVisibility(p))return next()
   const title=`${p.name} · ${p.specialty} | MELEO`
   const description=`${p.title||p.specialty} στην περιοχή ${p.city||p.region||'σου'}. ${p.verified?'MELEO Verified. ':''}${p.pricingMode==='from'?`Από ${p.price}€ βασική επίσκεψη.`:'Κόστος κατόπιν επικοινωνίας.'}`
   const canonical=`${config.appUrl}/professionals/${p.id}`
   const body=`<section><h1>${htmlEscape(p.name)}</h1><p>${htmlEscape(p.specialty)} · ${htmlEscape(p.city)}</p><p>${htmlEscape(p.bio||'')}</p></section>`
   const jsonLd={'@context':'https://schema.org','@type':'Person',name:p.name,jobTitle:p.title||p.specialty,address:{'@type':'PostalAddress',addressLocality:p.city,addressRegion:p.region,addressCountry:String(p.countryCode||'GR').toUpperCase()},url:canonical}
   res.type('html').send(injectSeo(baseHtml(),{title,description,canonical,body,jsonLd}))
 })
 app.get('/care/:specialty/:city',async(req,res,next)=>{
   const rows=await many(`SELECT DISTINCT specialty,city FROM professionals WHERE verified=true AND admin_suspended=false AND subscription_status='active' AND specialty<>'' AND city<>'' LIMIT 3000`)
   const match=rows.find(x=>slugify(x.specialty)===req.params.specialty&&slugify(x.city)===req.params.city);if(!match)return next()
   const count=await one(`SELECT count(*)::int n FROM professionals WHERE verified=true AND admin_suspended=false AND subscription_status='active' AND specialty=$1 AND city=$2`,[match.specialty,match.city])
   const title=`${match.specialty} ${match.city} · Βρες επαγγελματία | MELEO`
   const description=`Βρες επαληθευμένους επαγγελματίες ${match.specialty} στην περιοχή ${match.city}. Σύγκρινε προφίλ, διαθεσιμότητα και στείλε αίτημα μέσω MELEO.`
   const canonical=`${config.appUrl}/care/${encodeURIComponent(req.params.specialty)}/${encodeURIComponent(req.params.city)}`
   const body=`<section><h1>${htmlEscape(match.specialty)} στην περιοχή ${htmlEscape(match.city)}</h1><p>${count.n} διαθέσιμες επιλογές στη MELEO.</p></section>`
   res.type('html').send(injectSeo(baseHtml(),{title,description,canonical,body}))
 })
 app.use(express.static(dist,{maxAge:'1h',etag:true}))
 app.get(/.*/,(_req,res)=>res.sendFile(path.join(dist,'index.html')))
}else app.get('/',(_req,res)=>res.json({service:'MELEO API',status:'online',version:APP_VERSION,releaseChannel:RELEASE_CHANNEL,architecture:'PostgreSQL relational + Redis multi-instance + background worker + observability + secure S3 object storage'}))

app.use((err,req,res,_next)=>{log.error('http.unhandled_error',{requestId:req.requestId,error:err});res.status(500).json({error:'Εσωτερικό σφάλμα. Δοκίμασε ξανά.'})})

// sweeps without global lock
setInterval(async()=>{try{
 await Sessions.sweep();await sql('DELETE FROM one_time_tokens WHERE expires_at<=now() OR used_at IS NOT NULL');await sql('DELETE FROM analytics_event_dedup WHERE expires_at<=now()');await sql("DELETE FROM rate_limits WHERE reset_at<=now()-interval '1 hour'");await sql('DELETE FROM geocode_cache WHERE expires_at<=now()');
 const pending=await many(`SELECT u.id,p.stripe_subscription_id FROM users u LEFT JOIN professionals p ON p.user_id=u.id WHERE u.deletion_pending=true LIMIT 20`);for(const x of pending){try{if(x.stripe_subscription_id&&getStripe())await getStripe().subscriptions.cancel(x.stripe_subscription_id);await Users.update(x.id,{deletion_pending:false,deleted_at:now(),name:'Deleted User',phone:'',account_status:'suspended'});await Sessions.revokeUser(x.id);await audit(null,'account.deletion.finalized',{userId:x.id})}catch(err){console.warn('[MELEO v5] deletion retry failed',x.id,err.message)}}
 }catch(e){console.error('[MELEO v5 sweep]',e.message)}},15*60_000).unref()

const server=app.listen(config.port,()=>{log.info('api.started',{version:APP_VERSION,url:`http://localhost:${config.port}`,instance:process.env.INSTANCE_ID||process.env.HOSTNAME||'local'});console.log(`MELEO v${APP_VERSION} relational API [${process.env.INSTANCE_ID||process.env.HOSTNAME||'local'}] → http://localhost:${config.port}`)})
async function shutdown(){server.close();try{await listener.query('UNLISTEN meleo_live');listener.release()}catch{}await closeRedis();await closePool();process.exit(0)}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown)
