import React, { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { api } from '../../lib/api'
import './profile-rc3d.css'

function Profile({p,user,favorite,toggleFav,setView,startBooking,trackProfessionalEvent,IdentityAvatar,priceLabel,priceNote}:any){
  const {t,i18n}=useTranslation()
  const [tab,setTab]=useState('about')
  const [reviews,setReviews]=useState<any[]>([])
  const [trust,setTrust]=useState<any>(p?.trust||null)
  useEffect(()=>{trackProfessionalEvent(p.id,'profile_view');api('/professionals/'+p.id+'/reviews?limit=50').then((d:any)=>setReviews(Array.isArray(d)?d:(d.items||[]))).catch(()=>setReviews([]));api('/professionals/'+p.id).then((d:any)=>setTrust((d.professional||d)?.trust||null)).catch(()=>{})},[p.id])
  const call=()=>trackProfessionalEvent(p.id,'phone_click')
  const tabs=[['about',t('profile.tabs.about')],['services',t('profile.tabs.services')],['availability',t('profile.tabs.availability')],['credentials',t('profile.tabs.credentials')],['reviews',t('profile.tabs.reviews')]]
  return <section className="page rc3d-profile-page"><div className="container profile-layout"><div className="profile-main">
    <button className="back rc3d-profile-back" onClick={()=>setView('search')}>← {t('profile.back')}</button>
    <div className="profile-hero premium-profile"><IdentityAvatar name={p.name} photoUrl={p.profilePhotoUrl} avatarKey={p.avatarKey} size="xl"/><div className="profile-title"><div className="overline-row">{p.subscriptionPlan==='premium'&&<span className="featured inline">MELEO PREMIUM · {t('profile.recommended')}</span>}{p.verified&&<span className="verified-text">✓ MELEO Verified</span>}</div><h1>{p.name}</h1><p>{p.title} · {p.area?p.area+', ':''}{p.city}{p.countryCode?' · '+p.countryCode.toUpperCase():''}</p><div className="rating-row big"><span className="stars">★ {p.rating||t('profile.new')}</span><span>{t('profile.reviewCount',{count:p.reviews||0})}</span><span>· {t('profile.years',{count:p.years||0})}</span>{p.responseTime&&<span>· {t('profile.responds')} {p.responseTime}</span>}</div></div><button className={'heart standalone '+(favorite?'on':'')} aria-pressed={favorite} aria-label={favorite?t('profile.favorite.remove'):t('profile.favorite.add')} title={favorite?t('profile.favorite.removeTitle'):t('profile.favorite.addTitle')} onClick={()=>toggleFav(p.id)}>{favorite?'♥':'♡'}</button></div>
    <div className="profile-trust-grid"><span><b>✓</b> {t('profile.trust.verified')}</span><span><b>⌖</b> {t('profile.trust.radius',{count:p.serviceRadiusKm||15})}</span><span><b>⚡</b> {p.available}</span><span><b>◷</b> {p.responseTime||t('profile.trust.fast')}</span></div>
    {trust&&<div className={'meleo-trust-card '+(trust.eligible?'ready':'new')}><div className="trust-mark">M</div><div className="trust-copy"><small>MELEO TRUST</small>{trust.eligible?<><strong>{trust.score}<em>/100</em></strong><b>{trust.label}</b><span>{t('profile.trust.scoreText')}</span></>:<><strong className="trust-new">Verified</strong><b>{t('profile.trust.newPro')}</b><span>{t('profile.trust.newText')}</span></>}</div>{trust.eligible&&<div className="trust-mini"><span>★ {trust.rating}</span><span>✓ {t('profile.trust.completion',{count:trust.completionRate})}</span><span>↗ {t('profile.trust.response',{count:trust.responseRate})}</span></div>}</div>}
    <div className="profile-tabs" role="tablist" aria-label={t('profile.tabs.label')}>{tabs.map(([k,l])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>
    {tab==='about'&&<div className="content-card" role="tabpanel"><h3>{t('profile.about.title')}</h3><p>{p.bio}</p><div className="detail-pills">{(p.languages||['Ελληνικά']).map((x:string)=><span key={x}>🌐 {x}</span>)}</div></div>}
    {tab==='services'&&<div className="content-card" role="tabpanel"><h3>{t('profile.services.title')}</h3><div className="service-list">{p.services.map((x:string)=><div className="service-item" key={x}><span className="service-mark">+</span><div><b>{x}</b><small>{t('profile.services.note')}</small></div><strong>{(p.pricingMode||'from')==='contact'?t('profile.services.contact'):t('profile.services.from')}</strong></div>)}</div></div>}
    {tab==='availability'&&<div className="content-card" role="tabpanel"><h3>{t('profile.availability.title')}</h3><p className="muted">{t('profile.availability.note')}</p><div className="time-grid">{p.availability.map((x:string)=><span key={x}>{x}</span>)}</div></div>}
    {tab==='credentials'&&<div className="content-card" role="tabpanel"><h3>{t('profile.credentials.title')}</h3><div className="credential-list">{(p.credentials||[t('profile.credentials.fallback')]).map((x:string)=><div key={x}>✓ <span>{x}</span></div>)}</div></div>}
    {tab==='reviews'&&<div className="content-card" role="tabpanel"><h3>{reviews.length?t('profile.reviews.count',{count:reviews.length}):t('profile.reviews.empty')}</h3>{reviews.length>0&&<div className="review-highlight"><strong>{p.rating}</strong><span>★★★★★<small>{t('profile.reviews.average')}</small></span></div>}<div className="public-reviews">{reviews.map((x:any)=><div className="public-review" key={x.id}><div><b>{x.patientName}</b><span aria-label={t('profile.reviews.rating',{count:x.rating})}>{'★'.repeat(x.rating)}{'☆'.repeat(5-x.rating)}</span></div>{x.comment&&<p>{x.comment}</p>}<small>✓ {t('profile.reviews.verified')} · {new Date(x.createdAt).toLocaleDateString(i18n.language==='en'?'en-GB':'el-GR')}</small></div>)}</div><p className="muted">{t('profile.reviews.note')}</p></div>}
  </div><aside className="booking-panel sticky-premium"><div className="availability-top"><span className="pulse-dot" aria-hidden="true"/> {p.available}</div><div className="panel-price"><span>{t('profile.panel.baseCost')}</span><strong>{priceLabel(p)}</strong><small>{priceNote(p)}</small></div><div className="panel-feature">✓ {t('profile.panel.verified')}</div><div className="panel-feature">✓ {t('profile.panel.finalAgreement')}</div><div className="panel-feature">✓ {t('profile.panel.verifiedReviews')}</div>{p.phone&&<a className="btn btn-outline wide phone-cta" href={`tel:${p.phone}`} onClick={call}>☎ {t('profile.actions.call')}</a>}{p.email&&<a className="profile-email-link" href={`mailto:${p.email}`}>✉ {p.email}</a>}<button className="btn btn-dark wide" onClick={()=>user?startBooking():setView('auth')}>{user?t('profile.actions.request'):t('profile.actions.login')}</button><button className="btn btn-outline wide" onClick={()=>setView('now')}>⚡ {t('profile.actions.now')}</button><small className="panel-note">{t('profile.panel.disclaimer')}</small></aside></div></section>
}

export default Profile
