import React, { useEffect, useState } from 'react'
import { api } from '../../lib/api'
function SectionTitle({over,title,subtitle}:any){return <div className="section-title"><div className="eyebrow">{over}</div><h2>{title}</h2><p>{subtitle}</p></div>}
function Empty({title,text}:any){return <div className="empty"><div>◇</div><h3>{title}</h3><p>{text}</p></div>}
function NotificationsPage({user,token,setToast,embedded=false}:any){
 const [rows,setRows]=useState<any[]>([]);const [permission,setPermission]=useState(typeof Notification!=='undefined'?Notification.permission:'unsupported')
 async function load(){const d=await api('/notifications?limit=50',{},token);setRows(Array.isArray(d)?d:(d.items||[]))}useEffect(()=>{load();const f=()=>load();window.addEventListener('meleo:live',f);return()=>window.removeEventListener('meleo:live',f)},[])
 async function enable(){if(!('Notification'in window))return setToast('Ο browser δεν υποστηρίζει ειδοποιήσεις.');const p=await Notification.requestPermission();setPermission(p);setToast(p==='granted'?'Οι browser ειδοποιήσεις ενεργοποιήθηκαν.':'Δεν δόθηκε άδεια ειδοποιήσεων.')}
 async function mark(id:string){await api('/notifications/'+id+'/read',{method:'PATCH'},token);load()}
 const body=<div className="container narrow"><div className="notification-hero"><div><span>MELEO LIVE</span><h2>Ειδοποιήσεις</h2><p>Νέα αιτήματα, μηνύματα, προτάσεις κόστους, κρατήσεις και ενημερώσεις υποστήριξης εμφανίζονται ζωντανά.</p></div><button className="btn btn-dark" onClick={enable}>{permission==='granted'?'✓ Browser notifications ενεργές':'Ενεργοποίηση ειδοποιήσεων'}</button></div><div className="notification-list">{rows.length?rows.map(n=><button key={n.id} className={'notification-row '+(!n.read?'unread':'')} onClick={()=>mark(n.id)}><span>{n.type==='message'?'💬':n.type==='support'?'?':'🔔'}</span><div><b>{n.title}</b><p>{n.text}</p><small>{new Date(n.createdAt).toLocaleString('el-GR')}</small></div>{!n.read&&<i/>}</button>):<Empty title="Δεν υπάρχουν ειδοποιήσεις" text="Όταν υπάρξει νέα δραστηριότητα θα εμφανιστεί εδώ."/>}</div><div className="push-note">Οι live browser ειδοποιήσεις λειτουργούν όσο υπάρχει ενεργή σύνδεση με τη MELEO. Για background Web Push σε κλειστό browser απαιτείται production VAPID/Web-Push configuration.</div></div>
 return embedded?<div className="embedded-page">{body}</div>:<section className="page notifications-page">{body}</section>
}
function HelpCenter({user,token,setToast,cfg,embedded=false}:any){
 const [tickets,setTickets]=useState<any[]>([]);const [f,setF]=useState({subject:'',category:'booking',text:''});const [reply,setReply]=useState('')
 async function load(){if(user){const d=await api('/support/tickets?limit=50',{},token);setTickets(Array.isArray(d)?d:(d.items||[]))}}useEffect(()=>{load();const fn=()=>load();window.addEventListener('meleo:live',fn);return()=>window.removeEventListener('meleo:live',fn)},[user?.id])
 async function create(){if(!user)return setToast('Συνδέσου για να ανοίξεις αίτημα υποστήριξης.');await api('/support/tickets',{method:'POST',body:JSON.stringify(f)},token);setF({subject:'',category:'booking',text:''});await load();setToast('Το αίτημα υποστήριξης δημιουργήθηκε.')}
 async function send(id:string){if(!reply.trim())return;await api('/support/tickets/'+id+'/message',{method:'POST',body:JSON.stringify({text:reply})},token);setReply('');load()}
 const body=<div className="container"><SectionTitle over="MELEO SUPPORT" title="Help Center" subtitle="Άμεση βοήθεια για κρατήσεις, λογαριασμό, συνδρομές, verification και λειτουργία της πλατφόρμας."/><div className="help-grid"><div className="panel"><h3>Γρήγορες απαντήσεις</h3><div className="faq-list"><details><summary>Πώς λειτουργεί μια κράτηση;</summary><p>Αίτημα → διευκρινίσεις → τελικό κόστος → αποδοχή → επιβεβαιωμένη επίσκεψη.</p></details><details><summary>Πώς γίνεται το MELEO Verified;</summary><p>Ο επαγγελματίας υποβάλλει τα απαιτούμενα δικαιολογητικά και η ομάδα MELEO ολοκληρώνει τον έλεγχο.</p></details><details><summary>Πώς ακυρώνω συνδρομή;</summary><p>Από το Professional Dashboard → Συνδρομή. Η ακύρωση ισχύει στο τέλος της πληρωμένης περιόδου.</p></details><details><summary>Έχω επείγουσα ανάγκη.</summary><p>Η MELEO δεν είναι υπηρεσία επειγόντων. Σε επείγουσα κατάσταση κάλεσε {cfg?.emergencyNumber||'112'}.</p></details></div><a className="support-mail" href={`mailto:${cfg?.legal?.supportEmail||'support@meleo.gr'}`}>✉ {cfg?.legal?.supportEmail||'support@meleo.gr'}</a></div><div className="panel support-create"><h3>Νέο αίτημα υποστήριξης</h3>{user?<><label>Κατηγορία<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option value="booking">Κράτηση</option><option value="billing">Συνδρομή / Χρέωση</option><option value="verification">Verification</option><option value="account">Λογαριασμός</option><option value="technical">Τεχνικό θέμα</option><option value="general">Άλλο</option></select></label><label>Θέμα<input value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/></label><label>Περιγραφή<textarea value={f.text} onChange={e=>setF({...f,text:e.target.value})}/></label><button className="btn btn-dark" onClick={create}>Αποστολή στην υποστήριξη</button></>:<p>Συνδέσου για να δημιουργήσεις ticket και να παρακολουθείς τις απαντήσεις της ομάδας MELEO.</p>}</div></div>{user&&<div className="support-tickets"><h3>Τα αιτήματά μου</h3>{tickets.length?tickets.map(t=><div className="support-ticket" key={t.id}><div className="support-ticket-head"><div><b>{t.subject}</b><small>{t.category} · {new Date(t.createdAt).toLocaleString('el-GR')}</small></div><span className={'status '+(t.status==='closed'?'completed':'pending')}>{t.status}</span></div><div className="support-thread">{t.messages.map((m:any)=><div className={'support-message '+m.fromRole} key={m.id}><b>{m.fromName}</b><p>{m.text}</p><small>{new Date(m.createdAt).toLocaleString('el-GR')}</small></div>)}</div>{t.status!=='closed'&&<div className="support-reply"><input placeholder="Απάντηση…" value={reply} onChange={e=>setReply(e.target.value)}/><button onClick={()=>send(t.id)}>Αποστολή</button></div>}</div>):<Empty title="Δεν έχεις ανοικτά αιτήματα" text="Η ομάδα υποστήριξης είναι εδώ όταν τη χρειαστείς."/>}</div>}</div>
 return embedded?<div className="embedded-page">{body}</div>:<section className="page help-page">{body}</section>
}

export { NotificationsPage, HelpCenter }
